/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Cancion;

/**
 *
 * @author alejandroo
 */
public class VentanaMusica extends javax.swing.JFrame {

    String file;
    int idCancion = 1;

    /**
     * Creates new form VentanaMúsica
     */
    public VentanaMusica() {

        initComponents();
        btnGuardarAgreMusica.setEnabled(false);

    }

    public void validarDatos() {
        
        if (txtNombreCancion.getText().isEmpty()) {
            lblnombre.setText("*Campo Requerido");
        } else {
            lblnombre.setText("");
        }

        if (txtArtistaCancion.getText().isEmpty()) {
            lblartista.setText("*Campo Requerido");
        } else {
            lblartista.setText("");
        }

        if (txtTituloAlbum.getText().isEmpty()) {
            lblalbum.setText("*Campo Requerido");
        } else {
            lblalbum.setText("");
        }
        
         
        

        if (txtNombreCancion.getText().isEmpty() || txtArtistaCancion.getText().isEmpty() || txtTituloAlbum.getText().isEmpty() || jtRuta.getText().isEmpty()) {
            btnGuardarAgreMusica.setEnabled(false);
        } else {
            if(jtRuta.getText().contains(".mp3") || jtRuta.getText().contains(".wav")) {
                btnGuardarAgreMusica.setEnabled(true);
           
            }
            
        }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonAbrirArchivo = new javax.swing.JButton();
        txtNombreCancion = new javax.swing.JTextField();
        txtArtistaCancion = new javax.swing.JTextField();
        jComboEstilo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTituloAlbum = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        lblartista = new javax.swing.JLabel();
        lblalbum = new javax.swing.JLabel();
        lblarchivo = new javax.swing.JLabel();
        jtRuta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLimpiarAgreMusica = new javax.swing.JButton();
        btnSalirAgreMusica = new javax.swing.JButton();
        btnGuardarAgreMusica = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Música");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(56, 56, 56));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Canción");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Archivo:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Artista:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estilo:");

        jButtonAbrirArchivo.setBackground(new java.awt.Color(200, 226, 113));
        jButtonAbrirArchivo.setText("Abrir");
        jButtonAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirArchivoActionPerformed(evt);
            }
        });

        txtNombreCancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreCancionKeyReleased(evt);
            }
        });

        txtArtistaCancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArtistaCancionKeyReleased(evt);
            }
        });

        jComboEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Country", "Electronic dance music (EDM)", "Hip-hop", "Indie rock", "Jazz", "K-pop", "Metal", "Oldies", "Pop", "Rap", "Rhythm & blues (R&B)", "Rock", "Classical", "Afrobeats", "Calypso", "Dancehall", "Mambo", "Mento", "Merengue", "Reggae", "Rocksteady", "Salsa", "Ska", "Soca", "Steel band music/pan music", "Zouk", "A capella", "Celtic chant", "Drum & bass", "Euro-disco", "Flamenco", "Glitch pop", "Grime", "Opera", "Polka", "Trance", "Bachata", "Balada", "Bossa nova", "Compas", "Cumbia", "Mariachi", "Mexican", "Mesitzo", "Ranchera", "Reggaeton", "Samba", "Tango", "Vallenatto", "American folk", "Bluegrass", "Blues", "Canadian folk", "Gospel", "Industrial", "Swing", "Tejano", "Zydeco" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Album:");

        txtTituloAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloAlbumKeyReleased(evt);
            }
        });

        lblnombre.setForeground(new java.awt.Color(255, 0, 51));

        lblartista.setForeground(new java.awt.Color(255, 0, 51));

        lblalbum.setForeground(new java.awt.Color(255, 0, 51));

        lblarchivo.setForeground(new java.awt.Color(255, 0, 51));
        lblarchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblarchivoKeyReleased(evt);
            }
        });

        jtRuta.setBackground(new java.awt.Color(56, 56, 56));
        jtRuta.setForeground(new java.awt.Color(255, 255, 255));
        jtRuta.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel12)
                                .addComponent(jLabel14)
                                .addComponent(jLabel7))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblalbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtArtistaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(lblartista, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButtonAbrirArchivo)
                                .addGap(18, 18, 18)
                                .addComponent(lblarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblartista, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtArtistaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblarchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAbrirArchivo)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(56, 56, 56));

        btnLimpiarAgreMusica.setBackground(new java.awt.Color(200, 226, 113));
        btnLimpiarAgreMusica.setText("Limpiar");
        btnLimpiarAgreMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAgreMusicaActionPerformed(evt);
            }
        });

        btnSalirAgreMusica.setBackground(new java.awt.Color(200, 224, 112));
        btnSalirAgreMusica.setText("Salir");
        btnSalirAgreMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgreMusicaActionPerformed(evt);
            }
        });

        btnGuardarAgreMusica.setBackground(new java.awt.Color(200, 226, 113));
        btnGuardarAgreMusica.setText("Guardar");
        btnGuardarAgreMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgreMusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGuardarAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSalirAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAgreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAgreMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgreMusicaActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirAgreMusicaActionPerformed

    private void btnLimpiarAgreMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAgreMusicaActionPerformed
        txtNombreCancion.setText("");
        txtArtistaCancion.setText("");
        txtTituloAlbum.setText("");
        jtRuta.setText("");
        lblarchivo.setText("");

    }//GEN-LAST:event_btnLimpiarAgreMusicaActionPerformed

    private void btnGuardarAgreMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgreMusicaActionPerformed

        // Rescatar y validar
        validarDatos();
        String nombreCancion;
        String estilo;
        String artistaCancion;
        String album;
        String archivoCancion;

        // Rescatar y validar
        nombreCancion = txtNombreCancion.getText();
        estilo = jComboEstilo.getSelectedItem().toString();
        artistaCancion = txtArtistaCancion.getText();
        album = txtTituloAlbum.getText();
        archivoCancion = file;

        // Crear objeto
        Cancion cancion1 = new Cancion(nombreCancion, estilo, artistaCancion, album, archivoCancion);

        // Guardar en BD
        Registro reg = new Registro();
        if (reg.buscarNombreCancion(nombreCancion).size() == 0 && reg.buscarArtistaCancion(artistaCancion).size() == 0) {
            if (reg.agregarCancion(cancion1)) {
                JOptionPane.showMessageDialog(this, "Se agrego Cancion " + nombreCancion, "InformaciÃ³n", JOptionPane.INFORMATION_MESSAGE);
                txtNombreCancion.setText("");
                txtArtistaCancion.setText("");
                txtTituloAlbum.setText("");
                jtRuta.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "NO se agrego Cancion " + nombreCancion, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La cancion ya existe " + nombreCancion, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarAgreMusicaActionPerformed

    private void jButtonAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirArchivoActionPerformed

        JFileChooser dlg = new JFileChooser();
        int option = dlg.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = dlg.getSelectedFile().getPath().toString();
            System.out.println(file);
        }

        jtRuta.setText(file);
        validarDatos();
        if (jtRuta.getText().isEmpty()) {
            lblarchivo.setText("*Campo Requerido");
        } else {
            if(jtRuta.getText().contains(".mp3") || jtRuta.getText().contains(".wav")){
                lblarchivo.setText("");
            }else{
                lblarchivo.setText("*Campo Requerido");
                JOptionPane.showMessageDialog(this, "Extension del Archivo incompatible", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }

       
        

    

    }//GEN-LAST:event_jButtonAbrirArchivoActionPerformed

    private void txtNombreCancionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCancionKeyReleased
        validarDatos();
    }//GEN-LAST:event_txtNombreCancionKeyReleased

    private void txtArtistaCancionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtistaCancionKeyReleased
        validarDatos();
    }//GEN-LAST:event_txtArtistaCancionKeyReleased

    private void txtTituloAlbumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloAlbumKeyReleased
        validarDatos();
    }//GEN-LAST:event_txtTituloAlbumKeyReleased

    private void lblarchivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblarchivoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblarchivoKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaMúsica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaMúsica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaMúsica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaMúsica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaMúsica().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAgreMusica;
    private javax.swing.JButton btnLimpiarAgreMusica;
    private javax.swing.JButton btnSalirAgreMusica;
    private javax.swing.JButton jButtonAbrirArchivo;
    private javax.swing.JComboBox<String> jComboEstilo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jtRuta;
    private javax.swing.JLabel lblalbum;
    private javax.swing.JLabel lblarchivo;
    private javax.swing.JLabel lblartista;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtArtistaCancion;
    private javax.swing.JTextField txtNombreCancion;
    private javax.swing.JTextField txtTituloAlbum;
    // End of variables declaration//GEN-END:variables

  
}
