/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Class.Reproductor;
import com.mysql.jdbc.PreparedStatement;
import controlador.Conexion;
import controlador.Registro;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cancion;
import modelo.Reproductor1;
import modelo.Usuario;

/**
 *
 * @author alejandroo
 */
public class VentanaReproductor extends javax.swing.JFrame {

    Reproductor1 r = new Reproductor1();
    String lblnombreCancion;
    String lblalbum;
    String lblnombreArtista;
    String infoCancion;
    String rutaAudio;
    String email;
    String nomArtista;

    /**
     * Creates new form Reproductor
     */
    public VentanaReproductor() throws Exception {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNombrecancion = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        jLcancionVerde = new javax.swing.JLabel();
        jLartistaVerde = new javax.swing.JLabel();
        jLalbumVerde = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListar = new javax.swing.JTable();
        btnCanciones = new javax.swing.JButton();
        jComboEstilo = new javax.swing.JComboBox<>();
        jLbuscarEstilo = new javax.swing.JLabel();
        btnEliminarCancion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtListarUsuario = new javax.swing.JTable();
        btnUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAgregarMusicaRep = new javax.swing.JMenuItem();
        miSalirRep = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reproductor");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(200, 228, 112));

        lblNombrecancion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombrecancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblArtista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblArtista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArtista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAlbum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlbum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLcancionVerde.setText("Canción");

        jLartistaVerde.setText("Artista");

        jLalbumVerde.setText("Album");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNombrecancion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLcancionVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLartistaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLalbumVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcancionVerde)
                    .addComponent(jLartistaVerde)
                    .addComponent(jLalbumVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombrecancion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/04.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/02.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jtListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Canción", "Estilo", "Artista", "Album", "Archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtListar);

        btnCanciones.setText("Buscar");
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        jComboEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Country", "Electronic dance music (EDM)", "Hip-hop", "Indie rock", "Jazz", "K-pop", "Metal", "Oldies", "Pop", "Rap", "Rhythm & blues (R&B)", "Rock", "Classical", "Afrobeats", "Calypso", "Dancehall", "Mambo", "Mento", "Merengue", "Reggae", "Rocksteady", "Salsa", "Ska", "Soca", "Steel band music/pan music", "Zouk", "A capella", "Celtic chant", "Drum & bass", "Euro-disco", "Flamenco", "Glitch pop", "Grime", "Opera", "Polka", "Trance", "Bachata", "Balada", "Bossa nova", "Compas", "Cumbia", "Mariachi", "Mexican", "Mesitzo", "Ranchera", "Reggaeton", "Samba", "Tango", "Vallenatto", "American folk", "Bluegrass", "Blues", "Canadian folk", "Gospel", "Industrial", "Swing", "Tejano", "Zydeco" }));

        jLbuscarEstilo.setForeground(new java.awt.Color(255, 255, 255));
        jLbuscarEstilo.setText("Buscar Estilo:");

        btnEliminarCancion.setBackground(new java.awt.Color(253, 37, 37));
        btnEliminarCancion.setText("Eliminar Cancion");
        btnEliminarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCancionMouseClicked(evt);
            }
        });

        jtListarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Usuario", "Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListarUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtListarUsuario);

        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setBackground(new java.awt.Color(253, 37, 37));
        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLbuscarEstilo)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminarCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCanciones))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCancion)
                    .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbuscarEstilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCanciones)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuario)
                    .addComponent(btnEliminarUsuario))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        miAgregarMusicaRep.setText("Agregar Música");
        miAgregarMusicaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarMusicaRepActionPerformed(evt);
            }
        });
        jMenu1.add(miAgregarMusicaRep);

        miSalirRep.setText("Salir");
        miSalirRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirRepActionPerformed(evt);
            }
        });
        jMenu1.add(miSalirRep);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        Registro rg = new Registro();

        if (rg.buscarArchivoCancion(rutaAudio).size() == 1) {

            try {
                r.AbrirFichero(rutaAudio);
                r.Play();

            } catch (Exception ex) {
                System.out.println("Error: " + ex.getMessage());
            }

        }
        lblNombrecancion.setText(lblnombreCancion);
        lblArtista.setText(lblnombreArtista);
        lblAlbum.setText(lblalbum);

    }//GEN-LAST:event_btnPlayActionPerformed


    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try {
            r.Stop();
        } catch (Exception ex) {
            Logger.getLogger(VentanaReproductor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void miAgregarMusicaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarMusicaRepActionPerformed
        new VentanaMusica().setVisible(true);
    }//GEN-LAST:event_miAgregarMusicaRepActionPerformed

    private void miSalirRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirRepActionPerformed
        dispose();
    }//GEN-LAST:event_miSalirRepActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed

        String nombreCancion;
        String estilo;
        String artistaCancion;
        String album;
        String archivoCancion;
        String estiloFiltro;

        List<Cancion> lista;

        Registro rg = new Registro();
        DefaultTableModel modelo = (DefaultTableModel) jtListar.getModel();

        modelo.setRowCount(0);

        estiloFiltro = jComboEstilo.getSelectedItem().toString();

        if (estiloFiltro.equals("Todos")) {
            lista = rg.buscarTodasCanciones();
        } else {
            lista = rg.buscarCancionesEstilo(estiloFiltro);
        }

        for (Cancion tmp : lista) {
            artistaCancion = tmp.getArtistaCancion();
            nombreCancion = tmp.getNombreCancion();
            album = tmp.getAlbum();
            estilo = tmp.getEstilo();
            archivoCancion = tmp.getArchivoCancion();

            modelo.addRow(new Object[]{nombreCancion, estilo, artistaCancion, album, archivoCancion});
        }

    }//GEN-LAST:event_btnCancionesActionPerformed

    private void btnEliminarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCancionMouseClicked
        Registro rg = new Registro();
        if (rg.buscarNombreCancion(infoCancion).size() == 1 && rg.buscarArtistaCancion(nomArtista).size() == 1){
            if (rg.eliminarCancion(infoCancion)) {
                JOptionPane.showMessageDialog(this, "Se elimino cancion " + infoCancion, "Información", JOptionPane.INFORMATION_MESSAGE);
                jtListar.updateUI();
            } else {
                JOptionPane.showMessageDialog(this, "NO Se elimino Cancion" + infoCancion, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO Se encontro Usuario " + infoCancion, "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnEliminarCancionMouseClicked

    private void jtListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListarMouseClicked

        int fila = jtListar.getSelectedRow();
        String valor = jtListar.getValueAt(fila, 0).toString();
        String valorArchivo = jtListar.getValueAt(fila, 4).toString();
        String nombreArtista = jtListar.getValueAt(fila, 2).toString();
        String album = jtListar.getValueAt(fila, 3).toString();
        lblnombreCancion = valor;
        lblnombreArtista = nombreArtista;
        lblalbum = album;

        rutaAudio = valorArchivo;
        infoCancion = valor;
        nomArtista = nombreArtista;
        System.out.println(valor);
        System.out.println(infoCancion);
    }//GEN-LAST:event_jtListarMouseClicked

    private void jtListarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListarUsuarioMouseClicked
        int fila = jtListarUsuario.getSelectedRow();
        String nomUsuario = jtListarUsuario.getValueAt(fila, 0).toString();
        String valorEmail = jtListarUsuario.getValueAt(fila, 1).toString();
        email = valorEmail;
        System.out.println(nomUsuario);
        System.out.println(valorEmail);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jtListarUsuarioMouseClicked

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        String nombreUsuario;
        String email;
        String estiloFiltro;
        List<Usuario> lista;

        Registro rg = new Registro();
        rg.buscarTodosUsuarios();

        DefaultTableModel modelo = (DefaultTableModel) jtListarUsuario.getModel();

        modelo.setRowCount(0);

        estiloFiltro = jComboEstilo.getSelectedItem().toString();

        lista = rg.buscarTodosUsuarios();

        for (Usuario tmp : lista) {
            nombreUsuario = tmp.getNombreUsuario();
            email = tmp.getEmail();

            modelo.addRow(new Object[]{nombreUsuario, email});
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        Registro rg = new Registro();
        if (rg.buscarUsuarioEmail(email).size() == 1) {
            if (rg.eliminarUsuario(email)) {
                JOptionPane.showMessageDialog(this, "Se elimino Usuario " + email, "InformaciÃ³n", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "NO Se elimino Usuario" + email, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NO Se encontro Usuario " + email, "Error", JOptionPane.ERROR_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Reproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Reproductor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnEliminarCancion;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox<String> jComboEstilo;
    private javax.swing.JLabel jLalbumVerde;
    private javax.swing.JLabel jLartistaVerde;
    private javax.swing.JLabel jLbuscarEstilo;
    private javax.swing.JLabel jLcancionVerde;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtListar;
    private javax.swing.JTable jtListarUsuario;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblNombrecancion;
    private javax.swing.JMenuItem miAgregarMusicaRep;
    private javax.swing.JMenuItem miSalirRep;
    // End of variables declaration//GEN-END:variables
}
