/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alejandroo
 */
public class YourMusicApp extends javax.swing.JFrame {

    /**
     * Creates new form YourMusicApp
     */
    public YourMusicApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagenFondo = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miReproductor = new javax.swing.JMenuItem();
        miAgregarMusica = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YourMusicApp");
        setResizable(false);

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicioYourMusic.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenFondoLayout = new javax.swing.GroupLayout(jPanelImagenFondo);
        jPanelImagenFondo.setLayout(jPanelImagenFondoLayout);
        jPanelImagenFondoLayout.setHorizontalGroup(
            jPanelImagenFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenFondoLayout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelImagenFondoLayout.setVerticalGroup(
            jPanelImagenFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mArchivo.setText("Archivo");

        miReproductor.setText("Reproductor");
        miReproductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReproductorActionPerformed(evt);
            }
        });
        mArchivo.add(miReproductor);

        miAgregarMusica.setText("Agregar Música");
        miAgregarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarMusicaActionPerformed(evt);
            }
        });
        mArchivo.add(miAgregarMusica);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        jMenuBar.add(mArchivo);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0); //finaliza la app
    }//GEN-LAST:event_miSalirActionPerformed

    private void miReproductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReproductorActionPerformed
        try {
            new VentanaReproductor().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(YourMusicApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miReproductorActionPerformed

    private void miAgregarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarMusicaActionPerformed
        new VentanaMusica().setVisible(true);
    }//GEN-LAST:event_miAgregarMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        Conexion db = new Conexion();
//        db.obtenerConexion();
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new YourMusicApp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanelImagenFondo;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem miAgregarMusica;
    private javax.swing.JMenuItem miReproductor;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
